### ISSUE TITLE
SyntaxError while integrated with nuxt js 3

### ISSUE THREAD

**Issue by HelloRWA** [thorswap/SwapKit#903]
### Current behavior

It shows the error:
```sh
  SyntaxError: The requested module '@psf/bitcoincashjs-lib' does not provide an export named 'TransactionBuilder'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:131:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:213:5)
  at async ModuleLoader.import (node:internal/modules/esm/loader:308:24)
  at async ViteNodeRunner.interopedImport (node_modules/.pnpm/vite-node@1.4.0/node_modules/vite-node/dist/client.mjs:383:28)
  at async ViteNodeRunner.directRequest (node_modules/.pnpm/vite-node@1.4.0/node_modules/vite-node/dist/client.mjs:253:24)
  at async ViteNodeRunner.cachedRequest (node_modules/.pnpm/vite-node@1.4.0/node_modules/vite-node/dist/client.mjs:189:14)
  at async ViteNodeRunner.dependencyRequest (node_modules/.pnpm/vite-node@1.4.0/node_modules/vite-node/dist/client.mjs:233:12)
  at async node_modules/.pnpm/@swapkit+sdk@1.0.2_@babel+core@7.24.3_@polkadot+util-crypto@12.6.2_fastestsmallesttextencoder_wvhcu6wkucfh3vpswcidayh6xy/node_modules/@swapkit/sdk/dist/index.js:1:31
  at async ViteNodeRunner.runModule (node_modules/.pnpm/vite-node@1.4.0/node_modules/vite-node/dist/client.mjs:362:5)
  at async ViteNodeRunner.directRequest (node_modules/.pnpm/vite-node@1.4.0/node_modules/vite-node/dist/client.mjs:346:5)

```

### Expected behavior

should not have error

### Functionality

- [ ] Swap
- [ ] Liquidity
- [ ] Savers
- [ ] Loan
- [ ] Wallet
- [ ] Transactions
- [ ] Api
- [X] Other

### Packages

- [X] @swapkit/sdk
- [ ] @swapkit/core
- [ ] @swapkit/api
- [ ] @swapkit/helpers
- [ ] @swapkit/tokens
- [ ] @swapkit/toolbox-cosmos
- [ ] @swapkit/toolbox-evm
- [ ] @swapkit/toolbox-utxo
- [ ] @swapkit/wallet-evm-extensions
- [ ] @swapkit/wallet-keepkey
- [ ] @swapkit/wallet-keplr
- [ ] @swapkit/wallet-keystore
- [ ] @swapkit/wallet-ledger
- [ ] @swapkit/wallet-okx
- [ ] @swapkit/wallet-trezor
- [ ] @swapkit/wallet-wc
- [ ] @swapkit/wallet-xdefi

### Details

Package versions:
```bash
# Paste the output of `<npm|yarn|pnpm|bun pm> ls --depth=0 | grep @swapkit` here
pnpm ls --depth=0 |grep @swapkit
@swapkit/sdk 1.0.2
```

**Comment by ice-chillios** [comment]
@HelloRWA workaround for that would be to create `.d.ts` file, add:

```.d.ts
declare module "@psf/bitcoincashjs-lib";
```

and include it in your `tsconfig.json` for now as `@psf/bitcoincashjs-lib` is outside of our possibility to fix and we are right now looking for some solution to replace.
